version: "2"
services:
    camdiscovery:
        # image: saurabhshandy/camerasdiscovery:latest 
        image: registry.gitlab.com/macherlabs/edgedevice/camerasdiscovery:master
        container_name: camdiscovery
        ports:
            - "8000:8000"
        restart: always
        network_mode: host
        logging:
        driver: "json-file"
        options:
            max-size: "12000m"